services:
  teeworlds-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tw_server
    volumes:
      - ./reinforcement_learning:/app/reinforcement_learning
      - ./teeworlds-game/build-server:/app/build-server
    ports:
      - "8304:8304/udp"
      - "8304:8304/tcp"
      - "8303:8303/udp"
      - "8303:8303/tcp"
    restart: unless-stopped

  visualizer:
    build:
      context: .
      dockerfile: Dockerfile.visualizer
    container_name: tw_visualizer
    volumes:
      - ./reinforcement_learning:/app/reinforcement_learning
    ports:
      - "5000:5000/tcp"
    restart: unless-stopped