services:
  teeworlds-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tw_server
    volumes:
      - ./reinforcement_learning:/app/reinforcement_learning
      - ./teeworlds-game/build-server:/app/build-server
    ports:
      - "8304:8304/udp"
      - "8304:8304/tcp"
      - "8303:8303/udp"
      - "8303:8303/tcp"
    restart: unless-stopped

  dashboard:
    image: python:3.11-alpine
    container_name: tw_dashboard
    volumes:
      - ./reinforcement_learning/src/utils/noVNC:/app/noVNC
      - ./reinforcement_learning/src/utils/noVNC_patch/novnc.patch:/app/patch/novnc.patch:ro
      - ./reinforcement_learning/src/utils/noVNC_patch/novnc_dashboard.patch:/app/patch/novnc_dashboard.patch:ro
      - ./reinforcement_learning/src/utils/noVNC_patch/patch_entrypoint.sh:/app/patch/patch_entrypoint.sh:ro
    working_dir: /app/noVNC
    entrypoint: ["/bin/sh", "/app/patch/patch_entrypoint.sh"]
    ports:
      - "8080:8080"
    restart: unless-stopped