services:
  teeworlds-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: tw_server
    volumes:
      - ./reinforcement_learning:/app/reinforcement_learning
      - ./teeworlds-game/build-server:/app/build-server
    ports:
      - "8304:8304/udp"
      - "8304:8304/tcp"
      - "8303:8303/udp"
      - "8303:8303/tcp"
    restart: unless-stopped

dashboard:
    image: python:3.11-alpine
    container_name: tw_dashboard
    volumes:
      - ./reinforcement_learning/utils/noVNC:/app/noVNC
    working_dir: /app/noVNC
    command: ["python", "-m", "http.server", "8080"]
    ports:
      - "8080:8080"
    restart: unless-stopped