FROM alpine:latest

WORKDIR /app

COPY ./reinforcement_learning/configs/server.cfg /app/reinforcement_learning/configs/server.cfg

RUN apk add --no-cache \
    bash \
    zlib \
    openssl \
    libstdc++ \
    libgcc

CMD ["bash", "reinforcement_learning/scripts/launch_server.sh", "/app/build-server/teeworlds_srv"]